create table if not exists notatblokker (
    "blokkId" integer generated by default as identity primary key,
    interesse text, -- nullable
    emne text, -- nullable
    navn text not null,
    opprettelsesdato timestamptz not null default now(),
    antall_notater integer not null default 0,
    constraint emne_eller_interesse check (interesse is not null or emne is not null)
);


create table if not exists notater (
    "notatId" integer generated by default as identity primary key,
    interesse text, -- nullable
    emne text, -- nullable 
    tittel text not null,
    innhold text not null,
    opprettelsesdato timestamptz not null default now(),
    "blokkId" integer references notatblokker("blokkId") on delete cascade,
    constraint emne_eller_interesse check (interesse is not null or emne is not null)
);

-- helpful indexes
CREATE INDEX IF NOT EXISTS idx_notater_blokk ON notater("blokkId");
CREATE INDEX IF NOT EXISTS idx_notatblokker_emne   ON notatblokker(emne);
CREATE INDEX IF NOT EXISTS idx_notatblokker_interesse ON notatblokker(interesse);
CREATE INDEX IF NOT EXISTS idx_notater_emne        ON notater(emne);
CREATE INDEX IF NOT EXISTS idx_notater_interesse   ON notater(interesse);
