create table if not exists emner (
    id integer generated by default as identity primary key,
    navn text not null,
    opprettet timestamptz not null default now()
)

create table if not exists interesser (
    id integer generated by default as identity primary key,
    navn text not null,
    opprettet timstamptz not null default now()
)